// samples.js — A small set of real, well-known clinical references used as
// demo data so the app shows content on first open. Tags intentionally include
// aliases (e.g. 心梗 / mi, sepis) to demonstrate synonym merging.
//
// Entries are plain input objects; the store normalizes them on add.

export const SAMPLE_ENTRIES = [
  {
    title: 'The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)',
    type: 'guideline',
    authors: 'Singer M, Deutschman CS, Seymour CW, Shankar-Hari M, Annane D, Bauer M, Bellomo R, Bernard GR, Chiche JD, Coopersmith CM, Hotchkiss RS, Levy MM, Marshall JC, Martin GS, Opal SM, Rubenfeld GD, van der Poll T, Vincent JL, Angus DC',
    year: 2016,
    source: 'JAMA',
    doi: '10.1001/jama.2016.0287',
    url: 'https://doi.org/10.1001/jama.2016.0287',
    specialty: '重症医学',
    tags: ['脓毒症', 'sepis', 'sepsis-3', '休克'],
    evidenceLevel: 'high',
    rating: 5,
    notes: 'Sepsis-3 定义：感染引起的致命性器官功能障碍（SOFA 评分上升 ≥2）；脓毒性休克为需血管活性药维持血压且乳酸 >2 mmol/L。',
  },
  {
    title: '2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults',
    type: 'guideline',
    authors: 'Whelton PK, Carey RM, Aronow WS, Casey DE, Collins KJ, Dennison Himmelfarb C, DePalma SM, Gidding S, Jamerson KA, Jones DW, MacLaughlin EJ, Muntner P, Ovbiagele B, Smith SC, Spencer CC, Stafford RS, Taler SJ, Thomas RJ, Williams KA, Williamson JD, Wright JT',
    year: 2018,
    source: 'Hypertension',
    doi: '10.1161/HYP.0000000000000065',
    url: 'https://doi.org/10.1161/HYP.0000000000000065',
    specialty: '心血管内科',
    tags: ['高血压', 'htn', '指南'],
    evidenceLevel: 'high',
    rating: 5,
    notes: '美国高血压诊断阈值下调至 ≥130/80 mmHg，并强调心血管风险强化分层。',
  },
  {
    title: '2020 ESC Guidelines for the diagnosis and management of atrial fibrillation',
    type: 'guideline',
    authors: 'Hindricks G, Potpara T, Dagres N, Bax JJ, Blomström-Lundqvist C, Boriana G, Castella M, Dan GA, Dilaveris P, Fauchier L, Filippatos G, Kalman J, La Meir M, Lane D, Lebeau JP, Lettino M, Lip GYH, Pinto FJ, Thomas GN, Valgimigli M, Van Gelder IC, Van Putte B, Watkins CL',
    year: 2021,
    source: 'European Heart Journal',
    doi: '10.1093/eurheartj/ehaa612',
    url: 'https://doi.org/10.1093/eurheartj/ehaa612',
    specialty: '心血管内科',
    tags: ['房颤', 'af', '抗凝', '指南'],
    evidenceLevel: 'high',
    rating: 5,
    notes: '强调 ABC 管理路径：Anticoagulation（抗凝）、Better symptom control（症状控制）、Cardiovascular risk factors（合并症管理）。',
  },
  {
    title: 'Acute Respiratory Distress Syndrome: The Berlin Definition',
    type: 'guideline',
    authors: 'ARDS Definition Task Force, Ranieri VM, Rubenfeld GD, Thompson BT, Ferguson ND, Caldwell E, Fan E, Camporota L, Slutsky AS',
    year: 2012,
    source: 'JAMA',
    doi: '10.1001/jama.2012.5671',
    url: 'https://doi.org/10.1001/jama.2012.5671',
    specialty: '呼吸与危重症',
    tags: ['ards', '急性呼吸窘迫综合征', '呼吸衰竭'],
    evidenceLevel: 'high',
    rating: 4,
    notes: '按 PaO2/FiO2 分为轻（200–300）、中（100–200）、重（<100 mmHg）三型，并需 PEEP ≥5 cmH2O。',
  },
  {
    title: '2023 ESC Guidelines for the management of acute coronary syndromes',
    type: 'guideline',
    authors: 'Byrne RA, Rossello X, Coughlan JJ, Barbato E, Berry C, Chieffo A, Claeys MJ, Dan GA, Dweck MR, Galbraith M, Gilard M, Hinterbuchner L, Janssens S, Jensen LO, Kastrati A, Koller A, Scerbo D, Terricabras M, Tumscitz C, van der Ent M, Windecker S, Zena M, Zuarino A',
    year: 2023,
    source: 'European Heart Journal',
    doi: '10.1093/eurheartj/ehad191',
    url: 'https://doi.org/10.1093/eurheartj/ehad191',
    specialty: '心血管内科',
    tags: ['心梗', 'mi', '急性冠脉综合征', '指南'],
    evidenceLevel: 'high',
    rating: 5,
    notes: '急性冠脉综合征（含 STEMI / NSTEMI）的再灌注与抗栓策略更新。',
  },
  {
    title: 'Diagnosis and Classification of Diabetes Mellitus: Standards of Care in Diabetes—2024',
    type: 'guideline',
    authors: 'American Diabetes Association',
    year: 2024,
    source: 'Diabetes Care',
    doi: '10.2337/dc24-S002',
    url: 'https://doi.org/10.2337/dc24-S002',
    specialty: '内分泌科',
    tags: ['糖尿病', 'dm', '指南'],
    evidenceLevel: 'high',
    rating: 5,
    notes: '糖尿病诊断（空腹血糖、OGTT 2h、HbA1c、随机血糖+症状）与分型标准。',
  },
];
